---
- hosts: all
  become: true
  vars:
    apache_port: 80
    apache_root: "/var/www/html"
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
    - name: Configure Apache2
      template:
        src: templates/apache2.conf.j2
        dest: /etc/apache2/apache2.conf
      notify: Restart Apache2

  handlers:
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
